//! The routes in the contract: the routes a native client uses. Adding a route
//! here is a contract change; removing one is a breaking change that bumps
//! `API_CONTRACT` in `lib/api-contract.ts`.

use utoipa::openapi::HttpMethod;

/// Who may call an operation.
#[derive(Clone, Copy)]
pub(super) enum Security {
    None,
    Cookie,
    BearerOrCookie,
}

/// How a query value reads. Every query value is a string on the wire; this
/// tells a generated client what to accept, and the route coerces it.
#[derive(Clone, Copy)]
pub(super) enum QueryKind {
    String,
    Integer,
    /// `"true"` or `"false"`.
    Boolean,
    DateTime,
}

pub(super) struct Query {
    pub(super) name: &'static str,
    pub(super) kind: QueryKind,
    pub(super) description: &'static str,
    pub(super) required: bool,
}

pub(super) struct Operation {
    pub(super) method: HttpMethod,
    /// The path, with `{bookId}` and `{id}` placeholders. Each placeholder is
    /// a required integer path parameter.
    pub(super) path: &'static str,
    pub(super) operation_id: &'static str,
    pub(super) summary: &'static str,
    pub(super) tag: &'static str,
    pub(super) security: Security,
    pub(super) query: &'static [Query],
    /// The component name of the request body, when the route takes one.
    pub(super) body: Option<&'static str>,
    /// The component name of the 200 response. Several names document a
    /// route whose response shape depends on a query parameter: the document
    /// writes `oneOf`.
    pub(super) response: &'static [&'static str],
    /// Error statuses that a client must handle as a different case, with
    /// their description. Each carries an `ApiError` body. Every operation
    /// also has a default error response.
    pub(super) errors: &'static [(u16, &'static str)],
}

pub(super) const OPERATIONS: &[Operation] = &[
    Operation {
        method: HttpMethod::Get,
        path: "/api/version",
        operation_id: "getVersion",
        summary: "Server version and contract number.",
        tag: "meta",
        security: Security::None,
        query: &[],
        body: None,
        response: &["Version"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/auth/login",
        operation_id: "login",
        summary: "Start a cookie session.",
        tag: "auth",
        security: Security::None,
        query: &[],
        body: Some("LoginBody"),
        response: &["User"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/auth/logout",
        operation_id: "logout",
        summary: "End the cookie session.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/auth/me",
        operation_id: "getMe",
        summary: "The authenticated user.",
        tag: "auth",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["User"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/auth/api-keys",
        operation_id: "listApiKeys",
        summary: "List the user's API keys.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: None,
        response: &["ApiKeyList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/auth/api-keys",
        operation_id: "createApiKey",
        summary: "Mint an API key. The plaintext is returned once.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: Some("CreateApiKeyBody"),
        response: &["ApiKeyCreated"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/auth/api-keys/{id}",
        operation_id: "deleteApiKey",
        summary: "Revoke an API key.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/books",
        operation_id: "listBooks",
        summary: "The books you are a member of, with your role in each.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["BookList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/books",
        operation_id: "createBook",
        summary: "Create a book.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateBookBody"),
        response: &["Book"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/books/{bookId}",
        operation_id: "updateBook",
        summary: "Rename a book or change its settings.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateBookBody"),
        response: &["Book"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/books/{bookId}",
        operation_id: "deleteBook",
        summary: "Delete a book and everything in it.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/books/{bookId}/members",
        operation_id: "listBookMembers",
        summary: "The members of a book and their roles.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["BookMemberList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/books/{bookId}/members",
        operation_id: "addBookMember",
        summary: "Add an existing user to a book. Owner only.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("AddBookMemberBody"),
        response: &["BookMember"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/books/{bookId}/members/{userId}",
        operation_id: "updateBookMember",
        summary: "Change a member's role. Owner only.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateBookMemberBody"),
        response: &["BookMember"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/books/{bookId}/members/{userId}",
        operation_id: "removeBookMember",
        summary: "Remove a member. An owner removes anyone; a member removes themselves.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/accounts",
        operation_id: "listAccounts",
        summary: "Root accounts with balances and one level of children.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "type",
                kind: QueryKind::String,
                description: "Only accounts of this type: asset, liability, equity, income, or expense.",
                required: false,
            },
            Query {
                name: "includeInactive",
                kind: QueryKind::Boolean,
                description: "Send true to include inactive accounts.",
                required: false,
            },
            Query {
                name: "asOfDate",
                kind: QueryKind::String,
                description: "Balances as of this date as YYYY-MM-DD.",
                required: false,
            },
        ],
        body: None,
        response: &["AccountNodeList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/accounts",
        operation_id: "createAccount",
        summary: "Create an account.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateAccountBody"),
        response: &["AccountNode"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/accounts/{id}",
        operation_id: "getAccount",
        summary: "One account with its children and balance.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["AccountDetail"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/b/{bookId}/accounts/{id}",
        operation_id: "updateAccount",
        summary: "Update an account.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateAccountBody"),
        response: &["AccountWithChildren"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/b/{bookId}/accounts/{id}",
        operation_id: "deleteAccount",
        summary: "Delete an account that has no transactions.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/transactions",
        operation_id: "listTransactions",
        summary: "Transactions, newest first. With includeMeta=true the response is a TransactionPage.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "accountId",
                kind: QueryKind::Integer,
                description: "Only transactions with a split in this account.",
                required: false,
            },
            Query {
                name: "accountIds",
                kind: QueryKind::String,
                description: "Comma-separated account ids.",
                required: false,
            },
            Query {
                name: "balanceAccountId",
                kind: QueryKind::Integer,
                description: "Account for startingBalance. Defaults to the first of accountIds.",
                required: false,
            },
            Query {
                name: "payeeId",
                kind: QueryKind::Integer,
                description: "Only transactions with this payee.",
                required: false,
            },
            Query {
                name: "recurringRuleId",
                kind: QueryKind::Integer,
                description: "Only transactions this rule created.",
                required: false,
            },
            Query {
                name: "startDate",
                kind: QueryKind::String,
                description: "Inclusive lower bound as YYYY-MM-DD.",
                required: false,
            },
            Query {
                name: "endDate",
                kind: QueryKind::String,
                description: "Inclusive upper bound as YYYY-MM-DD.",
                required: false,
            },
            Query {
                name: "includeMeta",
                kind: QueryKind::Boolean,
                description: "Send true to receive a TransactionPage instead of a TransactionList.",
                required: false,
            },
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Page size. Default 100. 0 means everything.",
                required: false,
            },
            Query {
                name: "offset",
                kind: QueryKind::Integer,
                description: "Rows to skip.",
                required: false,
            },
            Query {
                name: "ensureId",
                kind: QueryKind::Integer,
                description: "Extend the first page until it includes this transaction.",
                required: false,
            },
        ],
        body: None,
        response: &["TransactionList", "TransactionPage"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/transactions",
        operation_id: "createTransaction",
        summary: "Create a transaction. Splits must sum to zero.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateTransactionBody"),
        response: &["Transaction"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/transactions/{id}",
        operation_id: "getTransaction",
        summary: "One transaction with its relations.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Transaction"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/b/{bookId}/transactions/{id}",
        operation_id: "updateTransaction",
        summary: "Update a transaction. Splits, when sent, replace all existing splits.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateTransactionBody"),
        response: &["Transaction"],
        errors: &[(
            409,
            "The transaction changed after you loaded it. The server makes no change. This occurs only when you send expectedUpdatedAt.",
        )],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/b/{bookId}/transactions/{id}",
        operation_id: "deleteTransaction",
        summary: "Delete a transaction.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[Query {
            name: "expectedUpdatedAt",
            kind: QueryKind::DateTime,
            description: "The updatedAt value you loaded. When you send it and the transaction changed since, the delete is refused (HTTP 409) and nothing changes. Omit it to skip the check.",
            required: false,
        }],
        body: None,
        response: &["Success"],
        errors: &[(
            409,
            "The transaction changed after you loaded it. The server makes no change. This occurs only when you send expectedUpdatedAt.",
        )],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/payees",
        operation_id: "listPayees",
        summary: "Payees with usage counts.",
        tag: "payees",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "search",
                kind: QueryKind::String,
                description: "Case-insensitive substring filter.",
                required: false,
            },
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Maximum rows.",
                required: false,
            },
        ],
        body: None,
        response: &["PayeeList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/payees",
        operation_id: "createPayee",
        summary: "Create a payee, or return the existing one with the same normalized name.",
        tag: "payees",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreatePayeeBody"),
        response: &["PayeeRow"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/search",
        operation_id: "search",
        summary: "Search transactions, accounts, payees, and recurring rules.",
        tag: "search",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "q",
                kind: QueryKind::String,
                description: "Query text. A currency amount matches split amounts. Omitted or empty returns empty buckets.",
                required: false,
            },
            Query {
                name: "startDate",
                kind: QueryKind::String,
                description: "Inclusive lower bound as YYYY-MM-DD.",
                required: false,
            },
            Query {
                name: "endDate",
                kind: QueryKind::String,
                description: "Inclusive upper bound as YYYY-MM-DD.",
                required: false,
            },
        ],
        body: None,
        response: &["SearchResponse"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/investments/account-values",
        operation_id: "listAccountMarketValues",
        summary: "Market value per investment account.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[Query {
            name: "asOfDate",
            kind: QueryKind::String,
            description: "Value as of this date as YYYY-MM-DD.",
            required: false,
        }],
        body: None,
        response: &["AccountMarketValueList"],
        errors: &[],
    },
];
