//! The routes in the contract: the routes a native client uses. Adding a route
//! here is a contract change; removing one is a breaking change that bumps
//! `API_CONTRACT` in `lib/api-contract.ts`.

use utoipa::openapi::HttpMethod;

/// The investment-split 400 messages. `createTransaction` and
/// `updateTransaction` share them.
macro_rules! investment_split_errors {
    () => {
        "A malformed investment split item first fails with the message of its field, for example \"Invalid input: expected number, received undefined\" or \"Too small: expected number to be >=0\". An unknown action fails with an \"Invalid option\" message, and an investmentSplits value that is not an array fails with \"investmentSplits must be an array when provided\". An item that passes then fails with one of these messages: \"Invalid investment split values\" (a stock split lacks a splitNumerator or splitDenominator above 0); \"Invalid investment actions\" (a buy or sell with no gross amount, a fee with no amount, a gross amount that is too large, or a stock split with no ratio); \"One or more investment split securities do not belong to this book\"; \"Investment splits require a transaction split on an investment account\" (a buy or sell without a split on an investment account)."
    };
}

/// Who may call an operation.
#[derive(Clone, Copy)]
pub(super) enum Security {
    None,
    Cookie,
    BearerOrCookie,
}

/// How a query value reads. Every query value is a string on the wire; this
/// tells a generated client what to accept, and the route coerces it.
#[derive(Clone, Copy)]
pub(super) enum QueryKind {
    String,
    Integer,
    /// `"true"` or `"false"`.
    Boolean,
    DateTime,
}

pub(super) struct Query {
    pub(super) name: &'static str,
    pub(super) kind: QueryKind,
    pub(super) description: &'static str,
    pub(super) required: bool,
}

pub(super) struct Operation {
    pub(super) method: HttpMethod,
    /// The path, with `{bookId}` and `{id}` placeholders. Each placeholder is
    /// a required integer path parameter, except `{date}`: that one is a
    /// required string with the `date` format.
    pub(super) path: &'static str,
    pub(super) operation_id: &'static str,
    pub(super) summary: &'static str,
    pub(super) tag: &'static str,
    pub(super) security: Security,
    pub(super) query: &'static [Query],
    /// The component name of the request body, when the route takes one.
    pub(super) body: Option<&'static str>,
    /// The component name of the 200 response. Several names document a
    /// route whose response shape depends on a query parameter: the document
    /// writes `oneOf`.
    pub(super) response: &'static [&'static str],
    /// Error statuses that a client must handle as a different case, with
    /// their description. Each carries an `ApiError` body. Every operation
    /// also has a default error response.
    pub(super) errors: &'static [(u16, &'static str)],
}

pub(super) const OPERATIONS: &[Operation] = &[
    Operation {
        method: HttpMethod::Get,
        path: "/api/version",
        operation_id: "getVersion",
        summary: "Server version and contract number.",
        tag: "meta",
        security: Security::None,
        query: &[],
        body: None,
        response: &["Version"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/auth/login",
        operation_id: "login",
        summary: "Start a cookie session.",
        tag: "auth",
        security: Security::None,
        query: &[],
        body: Some("LoginBody"),
        response: &["User"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/auth/logout",
        operation_id: "logout",
        summary: "End the cookie session.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/auth/me",
        operation_id: "getMe",
        summary: "The authenticated user.",
        tag: "auth",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["User"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/auth/api-keys",
        operation_id: "listApiKeys",
        summary: "List the user's API keys.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: None,
        response: &["ApiKeyList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/auth/api-keys",
        operation_id: "createApiKey",
        summary: "Mint an API key. The plaintext is returned once.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: Some("CreateApiKeyBody"),
        response: &["ApiKeyCreated"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/auth/api-keys/{id}",
        operation_id: "deleteApiKey",
        summary: "Revoke an API key.",
        tag: "auth",
        security: Security::Cookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/books",
        operation_id: "listBooks",
        summary: "The books you are a member of, with your role in each.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["BookList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/books",
        operation_id: "createBook",
        summary: "Create a book.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateBookBody"),
        response: &["Book"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/books/{bookId}",
        operation_id: "updateBook",
        summary: "Rename a book or change its settings.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateBookBody"),
        response: &["Book"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/books/{bookId}",
        operation_id: "deleteBook",
        summary: "Delete a book and everything in it.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/books/{bookId}/members",
        operation_id: "listBookMembers",
        summary: "The members of a book and their roles.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["BookMemberList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/books/{bookId}/members",
        operation_id: "addBookMember",
        summary: "Add an existing user to a book. Owner only.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("AddBookMemberBody"),
        response: &["BookMember"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/books/{bookId}/members/{userId}",
        operation_id: "updateBookMember",
        summary: "Change a member's role. Owner only.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateBookMemberBody"),
        response: &["BookMember"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/books/{bookId}/members/{userId}",
        operation_id: "removeBookMember",
        summary: "Remove a member. An owner removes anyone; a member removes themselves.",
        tag: "books",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/accounts",
        operation_id: "listAccounts",
        summary: "Root accounts with balances and one level of children.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "type",
                kind: QueryKind::String,
                description: "Only accounts of this type: asset, liability, equity, income, or expense.",
                required: false,
            },
            Query {
                name: "includeInactive",
                kind: QueryKind::Boolean,
                description: "Send true to include inactive accounts.",
                required: false,
            },
            Query {
                name: "asOfDate",
                kind: QueryKind::String,
                description: "Balances as of this date as YYYY-MM-DD.",
                required: false,
            },
        ],
        body: None,
        response: &["AccountNodeList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/accounts",
        operation_id: "createAccount",
        summary: "Create an account.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateAccountBody"),
        response: &["AccountNode"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/accounts/{id}",
        operation_id: "getAccount",
        summary: "One account with its children and balance.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["AccountDetail"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/b/{bookId}/accounts/{id}",
        operation_id: "updateAccount",
        summary: "Update an account.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateAccountBody"),
        response: &["AccountWithChildren"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/b/{bookId}/accounts/{id}",
        operation_id: "deleteAccount",
        summary: "Delete an account that has no transactions.",
        tag: "accounts",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/transactions",
        operation_id: "listTransactions",
        summary: "Transactions, newest first. With includeMeta=true the response is a TransactionPage.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "accountId",
                kind: QueryKind::Integer,
                description: "Only transactions with a split in this account.",
                required: false,
            },
            Query {
                name: "accountIds",
                kind: QueryKind::String,
                description: "Comma-separated account ids.",
                required: false,
            },
            Query {
                name: "balanceAccountId",
                kind: QueryKind::Integer,
                description: "Account for startingBalance. Defaults to the first of accountIds.",
                required: false,
            },
            Query {
                name: "payeeId",
                kind: QueryKind::Integer,
                description: "Only transactions with this payee.",
                required: false,
            },
            Query {
                name: "recurringRuleId",
                kind: QueryKind::Integer,
                description: "Only transactions this rule created.",
                required: false,
            },
            Query {
                name: "startDate",
                kind: QueryKind::String,
                description: "Inclusive lower bound as YYYY-MM-DD.",
                required: false,
            },
            Query {
                name: "endDate",
                kind: QueryKind::String,
                description: "Inclusive upper bound as YYYY-MM-DD.",
                required: false,
            },
            Query {
                name: "includeMeta",
                kind: QueryKind::Boolean,
                description: "Send true to receive a TransactionPage instead of a TransactionList.",
                required: false,
            },
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Page size. Default 100. 0 means everything.",
                required: false,
            },
            Query {
                name: "offset",
                kind: QueryKind::Integer,
                description: "Rows to skip.",
                required: false,
            },
            Query {
                name: "ensureId",
                kind: QueryKind::Integer,
                description: "Extend the first page until it includes this transaction.",
                required: false,
            },
        ],
        body: None,
        response: &["TransactionList", "TransactionPage"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/transactions",
        operation_id: "createTransaction",
        summary: "Create a transaction. Splits must sum to zero.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateTransactionBody"),
        response: &["Transaction"],
        errors: &[(
            400,
            concat!(
                "The request is not valid. The message names the problem: a missing or invalid date, splits that do not sum to zero, an account that is not in this book, a check number on a transaction with no bank account, or \"Investment transactions require investmentSplits\" (a split on an investment account and no investmentSplits). ",
                investment_split_errors!()
            ),
        )],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/transactions/changes",
        operation_id: "listTransactionChanges",
        summary: "Delta sync. Without since, pages all transactions by ID. With since, gives the transactions that changed after that cursor.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "since",
                kind: QueryKind::Integer,
                description: "The cursor of an earlier response. Selects delta mode. Do not send it with afterId or limit.",
                required: false,
            },
            Query {
                name: "afterId",
                kind: QueryKind::Integer,
                description: "Full mode: give the transactions with a larger ID. Default 0.",
                required: false,
            },
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Full mode: page size. Default 2000, maximum 5000.",
                required: false,
            },
        ],
        body: None,
        response: &["TransactionChanges"],
        errors: &[(
            410,
            "The cursor is not usable: it is newer than the change log, the database was restored from a snapshot after the cursor was given, or more than 5000 transactions changed after it. Download all transactions again in full mode.",
        )],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/transactions/{id}",
        operation_id: "getTransaction",
        summary: "One transaction with its relations.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Transaction"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/b/{bookId}/transactions/{id}",
        operation_id: "updateTransaction",
        summary: "Update a transaction. Splits, when sent, replace all existing splits.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateTransactionBody"),
        response: &["Transaction"],
        errors: &[
            (
                400,
                concat!(
                    "The request is not valid. The message names the problem. It can be any message of createTransaction. Also: \"At least 2 splits are required, even for stock splits\" (you send investmentSplits for a transaction with fewer than two splits and send no splits, or `splits` has fewer than 2 items). ",
                    investment_split_errors!()
                ),
            ),
            (404, "The book has no transaction with this id."),
            (
                409,
                "The transaction changed after you loaded it. The server makes no change. This occurs only when you send expectedUpdatedAt.",
            ),
        ],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/b/{bookId}/transactions/{id}",
        operation_id: "deleteTransaction",
        summary: "Delete a transaction.",
        tag: "transactions",
        security: Security::BearerOrCookie,
        query: &[Query {
            name: "expectedUpdatedAt",
            kind: QueryKind::DateTime,
            description: "The updatedAt value you loaded. When you send it and the transaction changed since, the delete is refused (HTTP 409) and nothing changes. Omit it to skip the check.",
            required: false,
        }],
        body: None,
        response: &["Success"],
        errors: &[(
            409,
            "The transaction changed after you loaded it. The server makes no change. This occurs only when you send expectedUpdatedAt.",
        )],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/payees",
        operation_id: "listPayees",
        summary: "Payees with usage counts.",
        tag: "payees",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "search",
                kind: QueryKind::String,
                description: "Case-insensitive substring filter.",
                required: false,
            },
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Maximum rows.",
                required: false,
            },
        ],
        body: None,
        response: &["PayeeList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/payees",
        operation_id: "createPayee",
        summary: "Create a payee, or return the existing one with the same normalized name.",
        tag: "payees",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreatePayeeBody"),
        response: &["PayeeRow"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/search",
        operation_id: "search",
        summary: "Search transactions, accounts, payees, and recurring rules.",
        tag: "search",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "q",
                kind: QueryKind::String,
                description: "Query text. A currency amount matches split amounts. Omitted or empty returns empty buckets.",
                required: false,
            },
            Query {
                name: "startDate",
                kind: QueryKind::String,
                description: "Inclusive lower bound as YYYY-MM-DD.",
                required: false,
            },
            Query {
                name: "endDate",
                kind: QueryKind::String,
                description: "Inclusive upper bound as YYYY-MM-DD.",
                required: false,
            },
        ],
        body: None,
        response: &["SearchResponse"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/investments/account-values",
        operation_id: "listAccountMarketValues",
        summary: "Market value per investment account.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[Query {
            name: "asOfDate",
            kind: QueryKind::String,
            description: "Value as of this date as YYYY-MM-DD.",
            required: false,
        }],
        body: None,
        response: &["AccountMarketValueList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/investments/positions",
        operation_id: "listInvestmentPositions",
        summary: "Positions: shares, cost basis and market value of each security.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[Query {
            name: "accountId",
            kind: QueryKind::Integer,
            description: "Count only this investment account. Zero or omitted means the whole book.",
            required: false,
        }],
        body: None,
        response: &["InvestmentPositionList"],
        errors: &[(400, "The accountId is not an integer.")],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities",
        operation_id: "listSecurities",
        summary: "Securities with position, price and income.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["SecurityList"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/securities",
        operation_id: "createSecurity",
        summary: "Create a security.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("CreateSecurityBody"),
        response: &["SecurityRow"],
        errors: &[
            (
                400,
                "A field is missing or not valid. The message names it.",
            ),
            (
                409,
                "The book already has a security with this symbol, compared without case.",
            ),
        ],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities/{id}",
        operation_id: "getSecurity",
        summary: "One security.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["SecurityRow"],
        errors: &[
            (400, "The security id is not an integer."),
            (404, "The book has no security with this id."),
        ],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/b/{bookId}/securities/{id}",
        operation_id: "updateSecurity",
        summary: "Update a security.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("UpdateSecurityBody"),
        response: &["SecurityRow"],
        errors: &[
            (
                400,
                "The security id is not an integer, no field is present, or a field is not valid. The message names it.",
            ),
            (404, "The book has no security with this id."),
            (
                409,
                "Another security of the book has this symbol, compared without case.",
            ),
        ],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/b/{bookId}/securities/{id}",
        operation_id: "deleteSecurity",
        summary: "Delete a security that has no investment transactions. Its prices are deleted with it.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[
            (
                400,
                "The security id is not an integer, or the security has investment transactions (\"Cannot delete security with investment transactions\").",
            ),
            (404, "The book has no security with this id."),
        ],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities/{id}/detail",
        operation_id: "getSecurityDetail",
        summary: "A security with its latest price, positions by account and all splits.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["SecurityDetail"],
        errors: &[
            (400, "The security id is not an integer."),
            (404, "The book has no security with this id."),
        ],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities/{id}/lots",
        operation_id: "listSecurityLots",
        summary: "Open lots of a security, oldest first.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["SecurityLotList"],
        errors: &[
            (400, "The security id is not an integer."),
            (404, "The book has no security with this id."),
        ],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities/{id}/splits",
        operation_id: "listSecuritySplits",
        summary: "Investment splits of a security, newest first, in pages.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Rows per page. The default is 50. The maximum is 200. A value that is not a positive integer gives the default.",
                required: false,
            },
            Query {
                name: "offset",
                kind: QueryKind::Integer,
                description: "Rows to skip. The default is 0. A value that is not a non-negative integer gives the default.",
                required: false,
            },
        ],
        body: None,
        response: &["SecuritySplitPage"],
        errors: &[
            (400, "The security id is not an integer."),
            (404, "The book has no security with this id."),
        ],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/reports/realized-gains",
        operation_id: "getRealizedGainsReport",
        summary: "Realized gains and losses of sells, by lot, with totals.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "startDate",
                kind: QueryKind::String,
                description: "First sell date as YYYY-MM-DD. Send it with endDate.",
                required: false,
            },
            Query {
                name: "endDate",
                kind: QueryKind::String,
                description: "Last sell date as YYYY-MM-DD. Send it with startDate.",
                required: false,
            },
            Query {
                name: "accountId",
                kind: QueryKind::Integer,
                description: "Count only this investment account. Must be positive.",
                required: false,
            },
        ],
        body: None,
        response: &["RealizedGainsReport"],
        errors: &[(
            400,
            "A date is not valid, only one of startDate and endDate is present, or accountId is not a positive integer.",
        )],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities/{id}/prices",
        operation_id: "listSecurityPrices",
        summary: "Price entries of a security, newest first, in pages. A date range can limit them.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[
            Query {
                name: "limit",
                kind: QueryKind::Integer,
                description: "Rows per page. The default is 50. The maximum is 5000. A value that is not a positive integer gives the default.",
                required: false,
            },
            Query {
                name: "offset",
                kind: QueryKind::Integer,
                description: "Rows to skip. The default is 0. A value that is not a non-negative integer gives the default.",
                required: false,
            },
            Query {
                name: "startDate",
                kind: QueryKind::String,
                description: "First price date as YYYY-MM-DD, included. An empty value means no lower bound.",
                required: false,
            },
            Query {
                name: "endDate",
                kind: QueryKind::String,
                description: "Last price date as YYYY-MM-DD, included. An empty value means no upper bound.",
                required: false,
            },
        ],
        body: None,
        response: &["SecurityPricePage"],
        errors: &[
            (
                400,
                "The security id is not an integer, a date is not valid, or startDate is after endDate.",
            ),
            (404, "The book has no security with this id."),
        ],
    },
    Operation {
        method: HttpMethod::Put,
        path: "/api/b/{bookId}/securities/{id}/prices/{date}",
        operation_id: "putSecurityPrice",
        summary: "Change the price entry of a date, or move it to another date. This is not an upsert: it never adds an entry. Use bulkUpdatePrices to add one.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("PutSecurityPriceBody"),
        response: &["Success"],
        errors: &[
            (
                400,
                "The security id is not an integer, or priceDate or priceMicros is not valid. The message names it.",
            ),
            (
                404,
                "The book has no security with this id, or the security has no price entry on the path date (\"Price entry not found\").",
            ),
            (
                409,
                "The body priceDate differs from the path date, and the security already has an entry on it.",
            ),
        ],
    },
    Operation {
        method: HttpMethod::Delete,
        path: "/api/b/{bookId}/securities/{id}/prices/{date}",
        operation_id: "deleteSecurityPrice",
        summary: "Delete the price entry of a date.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["Success"],
        errors: &[
            (400, "The security id is not an integer."),
            (
                404,
                "The book has no security with this id, or the security has no price entry on the path date (\"Price entry not found\").",
            ),
        ],
    },
    Operation {
        method: HttpMethod::Get,
        path: "/api/b/{bookId}/securities/prices-due",
        operation_id: "listPricesDue",
        summary: "Manually priced securities with an open position and no price on the last market day.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: None,
        response: &["PricesDue"],
        errors: &[],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/security-prices/bulk",
        operation_id: "bulkUpdatePrices",
        summary: "Write many manual prices in one transaction. An entry on the same date is replaced and keeps its source. A new entry gets the source manual.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("BulkUpdatePricesBody"),
        response: &["BulkUpdatePricesResult"],
        errors: &[(
            400,
            "priceUpdates is not an array, no item is valid, or a security is not in this book. Nothing is written.",
        )],
    },
    Operation {
        method: HttpMethod::Post,
        path: "/api/b/{bookId}/security-prices/tiingo",
        operation_id: "fetchTiingoPrices",
        summary: "Fetch the latest Tiingo price of each symbol. The server writes no price.",
        tag: "investments",
        security: Security::BearerOrCookie,
        query: &[],
        body: Some("FetchTiingoPricesBody"),
        response: &["FetchTiingoPricesResult"],
        errors: &[
            (400, "symbols is missing or empty."),
            (
                500,
                "The server has no Tiingo key. The message is \"TIINGO_API_KEY environment variable not configured\".",
            ),
        ],
    },
];
