//! The component schemas of the contract, in document order. The name is the
//! name of the type that a native client generates.

use serde_json::json;
use utoipa::openapi::schema::{KnownFormat, Type};

use super::dsl::{
    Refine, S, array, boolean, integer, nullable, object, reference, string, string_enum, types,
};

#[allow(clippy::too_many_lines)]
pub(super) fn components() -> Vec<(&'static str, S)> {
    vec![
        ("Cents", integer().describe("Money in integer cents. Positive is a debit, negative is a credit.")),
        ("Micros", integer().describe("Shares or a price in micros. 1,000,000 micros is one share or one dollar.")),
        ("LedgerDate", string().format(KnownFormat::Date).describe("A calendar date as YYYY-MM-DD. No time zone.")),
        ("Timestamp", string().format(KnownFormat::DateTime).describe("A UTC instant as an ISO 8601 string with a Z suffix.")),
        ("Success", object(vec![("success", boolean().constant(json!(true)), true)])),
        ("ApiError", object(vec![("error", string().describe("A message safe to show to the user."), true)])),
        ("AccountType", string_enum(&["asset", "liability", "equity", "income", "expense"])),
        ("AccountSubtype", string_enum(&["bank", "credit_card", "loan", "investment", "cash", "other"])),
        ("AccountRow", object(vec![("id", integer(), true), ("bookId", integer(), true), ("name", string(), true), ("type", reference("AccountType"), true), ("subtype", nullable(reference("AccountSubtype")), true), ("parentId", nullable(integer()), true), ("isActive", boolean(), true), ("isFavorite", boolean(), true), ("isInvestmentCash", boolean(), true), ("icon", types(&[Type::String, Type::Null]).describe("A single emoji, or null to inherit the parent's icon."), true), ("createdAt", reference("Timestamp"), true), ("updatedAt", reference("Timestamp"), true)])),
        ("AccountNode", object(vec![("id", integer(), true), ("bookId", integer(), true), ("name", string(), true), ("type", reference("AccountType"), true), ("subtype", nullable(reference("AccountSubtype")), true), ("parentId", nullable(integer()), true), ("isActive", boolean(), true), ("isFavorite", boolean(), true), ("isInvestmentCash", boolean(), true), ("icon", types(&[Type::String, Type::Null]).describe("A single emoji, or null to inherit the parent's icon."), true), ("createdAt", reference("Timestamp"), true), ("updatedAt", reference("Timestamp"), true), ("balance", reference("Cents"), true), ("hasTransactions", boolean(), true), ("children", array(reference("AccountNode")), true)])),
        ("AccountNodeList", array(reference("AccountNode"))),
        ("AccountDetail", object(vec![("id", integer(), true), ("bookId", integer(), true), ("name", string(), true), ("type", reference("AccountType"), true), ("subtype", nullable(reference("AccountSubtype")), true), ("parentId", nullable(integer()), true), ("isActive", boolean(), true), ("isFavorite", boolean(), true), ("isInvestmentCash", boolean(), true), ("icon", types(&[Type::String, Type::Null]).describe("A single emoji, or null to inherit the parent's icon."), true), ("createdAt", reference("Timestamp"), true), ("updatedAt", reference("Timestamp"), true), ("children", array(reference("AccountRow")), true), ("balance", reference("Cents"), true), ("hasTransactions", boolean(), true)])),
        ("AccountWithChildren", object(vec![("id", integer(), true), ("bookId", integer(), true), ("name", string(), true), ("type", reference("AccountType"), true), ("subtype", nullable(reference("AccountSubtype")), true), ("parentId", nullable(integer()), true), ("isActive", boolean(), true), ("isFavorite", boolean(), true), ("isInvestmentCash", boolean(), true), ("icon", types(&[Type::String, Type::Null]).describe("A single emoji, or null to inherit the parent's icon."), true), ("createdAt", reference("Timestamp"), true), ("updatedAt", reference("Timestamp"), true), ("children", array(reference("AccountRow")), true)])),
        ("User", object(vec![("id", integer(), true), ("username", string(), true)])),
        ("LoginBody", object(vec![("username", string().min_length(1), true), ("password", string().min_length(1), true)])),
        ("ApiKeyCreated", object(vec![("id", integer(), true), ("name", string(), true), ("key", string().describe("The plaintext key. It is returned once and never again."), true), ("keyPrefix", string(), true), ("createdAt", reference("Timestamp"), true)])),
        ("ApiKeyListItem", object(vec![("id", integer(), true), ("name", string(), true), ("keyPrefix", string(), true), ("lastUsedAt", nullable(reference("Timestamp")), true), ("createdAt", reference("Timestamp"), true)])),
        ("ApiKeyList", array(reference("ApiKeyListItem"))),
        ("BookMember", object(vec![("userId", integer(), true), ("username", string(), true), ("role", string_enum(&["owner", "editor", "viewer"]), true), ("createdAt", reference("Timestamp"), true)])),
        ("BookMemberList", array(reference("BookMember"))),
        ("Book", object(vec![("id", integer(), true), ("userId", integer(), true), ("name", string(), true), ("upcomingDays", integer(), true), ("typesafeReconciliationEnabled", boolean(), true), ("typesafeRevision", integer(), true), ("createdAt", reference("Timestamp"), true), ("updatedAt", reference("Timestamp"), true), ("role", string_enum(&["owner", "editor", "viewer"]).describe("Your role in this book: owner, editor or viewer. Present in the book list."), false)])),
        ("BookList", array(reference("Book"))),
        ("AccountMarketValue", object(vec![("accountId", integer(), true), ("marketValueCents", reference("Cents"), true)])),
        ("AccountMarketValueList", array(reference("AccountMarketValue"))),
        ("PayeeRow", object(vec![("id", integer(), true), ("bookId", integer(), true), ("name", string(), true), ("createdAt", reference("Timestamp"), true)])),
        ("PayeeListItem", object(vec![("id", integer(), true), ("name", string(), true), ("lastTransactionDate", nullable(reference("LedgerDate")), true), ("transactionCount", integer(), true)])),
        ("PayeeList", array(reference("PayeeListItem"))),
        ("SearchTransaction", object(vec![("id", integer(), true), ("date", reference("LedgerDate"), true), ("description", types(&[Type::String, Type::Null]), true), ("checkNumber", types(&[Type::String, Type::Null]), true), ("payee", nullable(object(vec![("id", integer(), true), ("name", string(), true)])), true), ("splits", array(object(vec![("accountId", integer(), true), ("accountName", string(), true), ("amount", reference("Cents"), true), ("isFavorite", boolean(), true), ("subtype", types(&[Type::String, Type::Null]), true), ("isInvestmentCash", boolean(), true)])), true)])),
        ("SearchResponse", object(vec![("transactions", array(reference("SearchTransaction")), true), ("accounts", object(vec![("items", array(object(vec![("id", integer(), true), ("name", string(), true), ("type", reference("AccountType"), true), ("subtype", nullable(reference("AccountSubtype")), true), ("isFavorite", boolean(), true)])), true), ("total", integer(), true), ("truncated", boolean(), true)]), true), ("payees", object(vec![("items", array(object(vec![("id", integer(), true), ("name", string(), true)])), true), ("total", integer(), true), ("truncated", boolean(), true)]), true), ("recurringRules", object(vec![("items", array(object(vec![("id", integer(), true), ("name", string(), true), ("frequency", string(), true), ("nextDate", reference("LedgerDate"), true), ("businessDaysOnly", boolean(), true), ("isActive", boolean(), true)])), true), ("total", integer(), true), ("truncated", boolean(), true)]), true)])),
        ("SecurityRow", object(vec![("id", integer(), true), ("bookId", integer(), true), ("name", string(), true), ("symbol", string(), true), ("securityType", string_enum(&["etf", "mutual_fund", "stock"]), true), ("fetchPrices", boolean(), true), ("fixedPriceMicros", nullable(reference("Micros")), true), ("createdAt", reference("Timestamp"), true)])),
        ("TransactionSplit", object(vec![("id", integer(), true), ("bookId", integer(), true), ("transactionId", integer(), true), ("accountId", integer(), true), ("amount", reference("Cents"), true), ("account", reference("AccountRow"), true)])),
        ("InvestmentSplitRow", object(vec![("id", integer(), true), ("bookId", integer(), true), ("transactionId", integer(), true), ("accountId", nullable(integer()), true), ("securityId", integer(), true), ("action", string_enum(&["buy", "sell", "dividend", "capGain", "fee", "split"]), true), ("sharesMicros", reference("Micros"), true), ("priceMicros", reference("Micros"), true), ("feesCents", reference("Cents"), true), ("splitNumerator", nullable(integer()), true), ("splitDenominator", nullable(integer()), true), ("security", reference("SecurityRow"), true), ("account", nullable(reference("AccountRow")), true)])),
        ("Transaction", object(vec![("id", integer(), true), ("bookId", integer(), true), ("date", reference("LedgerDate").describe("The stored date. For a floating transaction the effective date is today; compute it on the client."), true), ("description", types(&[Type::String, Type::Null]), true), ("checkNumber", types(&[Type::String, Type::Null]), true), ("notes", types(&[Type::String, Type::Null]), true), ("payeeId", nullable(integer()), true), ("isReconciled", boolean(), true), ("isFloating", boolean(), true), ("recurringRuleId", nullable(integer()), true), ("createdBy", nullable(integer()).describe("The user who created this row. An older client contract omits this field. Null means a system write."), false), ("updatedBy", nullable(integer()).describe("The user who last changed this row. An older client contract omits this field. Null means a system write."), false), ("createdAt", reference("Timestamp"), true), ("updatedAt", reference("Timestamp"), true), ("payee", nullable(reference("PayeeRow")), true), ("splits", array(reference("TransactionSplit")), true), ("investmentSplits", array(reference("InvestmentSplitRow")), true)])),
        ("TransactionList", array(reference("Transaction"))),
        ("TransactionPage", object(vec![("transactions", array(reference("Transaction")), true), ("startingBalance", reference("Cents").describe("Sum of the balance account's splits older than the oldest transaction on this page."), true), ("totalCount", integer(), true)])),
        ("Version", object(vec![("version", string().describe("The server's package.json version."), true), ("apiContract", integer().describe("Increases on a breaking change to this contract."), true)])),
        ("CreateBookBody", object(vec![("name", string().min_length(1).describe("The book's name, shown in the book switcher and page titles."), true)])),
        ("UpdateBookBody", object(vec![("name", string().min_length(1).describe("The book's name, shown in the book switcher and page titles."), true), ("upcomingDays", integer().minimum(1).maximum(365).describe("How many days ahead recurring transactions are projected on the dashboard (integer, 1-365). Omit to leave it unchanged."), false)])),
        ("CreateAccountBody", object(vec![("name", string().min_length(1).describe("Account name, as it will appear in the chart of accounts."), true), ("type", string_enum(&["asset", "liability", "equity", "income", "expense"]).describe("Account type: asset, liability, equity, income, or expense. You cannot change this after creation."), true), ("subtype", nullable(string_enum(&["bank", "credit_card", "loan", "investment", "cash", "other"])).describe("Account subtype: bank, credit_card, loan, investment, cash, or other. Set to 'investment' to also create a paired cash sub-account automatically."), false), ("parentId", nullable(integer().exclusive_minimum(0)).describe("ID of the parent account, to nest this account under it. Omit for a top-level account. Use get_account_tree to find a parentId."), false), ("icon", types(&[Type::String, Type::Null]).describe("A single emoji to show for this account. Only income and expense accounts show an icon. Send null to inherit the icon from the parent account instead of setting one directly."), false)])),
        ("UpdateAccountBody", object(vec![("name", string().describe("New account name."), false), ("subtype", nullable(string_enum(&["bank", "credit_card", "loan", "investment", "cash", "other"])).describe("New account subtype: bank, credit_card, loan, investment, cash, or other."), false), ("parentId", nullable(integer().exclusive_minimum(0)).describe("New parent account ID, to move this account under it. Send null to make it a top-level account."), false), ("isActive", boolean().describe("Set to false to deactivate the account, or true to reactivate it. For an investment account, this also updates its paired cash sub-account."), false), ("isFavorite", boolean().describe("Set to true to mark the account as a favorite."), false), ("icon", types(&[Type::String, Type::Null]).describe("A single emoji to show for this account. Only income and expense accounts show an icon. Send null to inherit the icon from the parent account instead of setting one directly."), false)])),
        ("CreateTransactionBody", object(vec![("date", string().format(KnownFormat::Date).describe("Transaction date in YYYY-MM-DD format"), true), ("description", string().describe("Transaction description"), false), ("notes", string().describe("Additional notes"), false), ("payeeName", string().describe("Payee name. Matched case-insensitively to an existing payee in this book; created if none matches."), false), ("checkNumber", string().describe("Check number (only for bank account transactions)"), false), ("isFloating", boolean().describe("If true, the transaction's effective date auto-advances to today until reconciled. Useful for checks or expected deposits where the clearing date is unknown."), false), ("isReconciled", boolean().describe("If true, the transaction is recorded as already reconciled. If the transaction is floating (isFloating is true), also set isFloating to false and give the cleared date in the same call. If you set only isReconciled, the transaction stays floating, and its effective date keeps moving to today even though it is marked reconciled."), false), ("splits", array(object(vec![("accountId", integer().exclusive_minimum(0).describe("The account ID for this split"), true), ("amount", integer().describe("Amount in cents. Positive = debit, negative = credit. All splits must sum to zero."), true)])).min_items(2).describe("Transaction splits (must sum to zero)"), true), ("investmentSplits", array(object(vec![("securityId", integer().exclusive_minimum(0).describe("The security ID"), true), ("action", string_enum(&["buy", "sell", "dividend", "capGain", "fee", "split"]).describe("Investment action type"), true), ("sharesMicros", integer().minimum(0).describe("Number of shares in micros (1,000,000 = 1 share). Always positive."), true), ("priceMicros", integer().minimum(0).describe("Price per share in micros (1,000,000 = $1.00)"), true), ("feesCents", integer().minimum(0).describe("Fees in cents"), false), ("splitNumerator", integer().exclusive_minimum(0).describe("For stock split: new share ratio numerator"), false), ("splitDenominator", integer().exclusive_minimum(0).describe("For stock split: old share ratio denominator"), false)])).describe("Investment splits (required if transaction involves investment accounts)"), false)])),
        ("UpdateTransactionBody", object(vec![("date", string().format(KnownFormat::Date).describe("New date in YYYY-MM-DD format"), false), ("description", string().describe("New description"), false), ("notes", types(&[Type::String, Type::Null]).describe("New notes"), false), ("payeeName", types(&[Type::String, Type::Null]).describe("New payee name"), false), ("checkNumber", string().describe("New check number"), false), ("isFloating", boolean().describe("Set to true to make the transaction float (effective date = today). Set to false to stop floating."), false), ("isReconciled", boolean().describe("Set to true to mark the transaction reconciled. If the transaction is floating (isFloating is true), also set isFloating to false and set date to the cleared date in the same call. If you set only isReconciled, the transaction stays floating, and its effective date keeps moving to today even though it is marked reconciled."), false), ("splits", array(object(vec![("accountId", integer().exclusive_minimum(0).describe("The account ID for this split"), true), ("amount", integer().describe("Amount in cents. Positive = debit, negative = credit. All splits must sum to zero."), true)])).min_items(2).describe("New splits (replaces all existing, must sum to zero)"), false), ("investmentSplits", array(object(vec![("securityId", integer().exclusive_minimum(0).describe("The security ID"), true), ("action", string_enum(&["buy", "sell", "dividend", "capGain", "fee", "split"]).describe("Investment action type"), true), ("sharesMicros", integer().minimum(0).describe("Number of shares in micros (1,000,000 = 1 share). Always positive."), true), ("priceMicros", integer().minimum(0).describe("Price per share in micros (1,000,000 = $1.00)"), true), ("feesCents", integer().minimum(0).describe("Fees in cents"), false), ("splitNumerator", integer().exclusive_minimum(0).describe("For stock split: new share ratio numerator"), false), ("splitDenominator", integer().exclusive_minimum(0).describe("For stock split: old share ratio denominator"), false)])).describe("New investment splits (replaces all existing)"), false), ("expectedUpdatedAt", string().format(KnownFormat::DateTime).describe("The updatedAt value you loaded. When you send it and the transaction changed since, the update is refused (HTTP 409) and nothing changes. Omit it to skip the check."), false)])),
        ("CreatePayeeBody", object(vec![("name", string().min_length(1).describe("The payee's name. Normalized on save: whitespace runs collapse to one space and curly quotes straighten to '. Case is NOT changed — \"IKEA\" and \"Ikea\" stay two different payees."), true)])),
        ("CreateApiKeyBody", object(vec![("name", string().min_length(1), true)])),
        ("AddBookMemberBody", object(vec![("username", string().min_length(1).describe("The exact username of an existing user. Case matters."), true), ("role", string_enum(&["owner", "editor", "viewer"]).describe("owner: everything, including members, rename, delete and bank connections. editor: read and change the ledger. viewer: read only."), true)])),
        ("UpdateBookMemberBody", object(vec![("role", string_enum(&["owner", "editor", "viewer"]).describe("owner: everything, including members, rename, delete and bank connections. editor: read and change the ledger. viewer: read only."), true)])),
    ]
}
